name: Perl-Editor-Plugin-Squish
version: 0.01
abstract: A Perl::Editor plugin for Perl::Squish
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  Perl::Squish: 0.02
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
